#! /bin/bash

bspc monitor -d chat term  www archiver code media  
"$HOME"/.config/polybar/launch.sh &
sxhkd &
# -----------------------------------------
# bspwm config
# -----------------------------------------
bspc config window_gap          5
bspc config border_width        0
bspc config pointer_follows_focus false
#bspc config top_padding 20
bspc config bottom_padding  32 
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true
#------------------------------------------------
# Border Colors
#------------------------------------------------
bspc config focused_border_color        "#C12B4D"
bspc config focused_locked_border_color "#dc322f"
bspc config active_border_color         "#F5F6F7"
bspc config active_locked_border_color  "#d33682"
bspc config normal_border_color         "#222222"
bspc config normal_locked_border_color  "#3F3E3B"
bspc config presel_border_color         "#C12B4D"
bspc config urgent_border_color         "#93a1a1"
# -----------------------------------------------
# Rules
# -----------------------------------------------
bspc rule -a Firefox desktop=^3  floating=true
bspc rule -a Thunar desktop=^4 
bspc rule -a Telegram desktop=^1
